name: inject_generator
version: 1.0.0-alpha
description: Dev-time dependency for package:inject.
authors:
  - Matan Lurey <matanl@google.com>
  - Yegor Jbanov <yjbanov@google.com>
homepage: https://pub.dartlang.org/packages/inject

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  analyzer: ^0.39.1
  build:
  code_builder:
  collection:
  dart_style:
  logging:
  meta:
  path:
  quiver:
  stack_trace:

#  flutter:
#    sdk: flutter

dev_dependencies:
  build_runner:
  build_test:
  inject:
    path: ../inject
#  flutter_test:
#    sdk: flutter